---
- name: DEPROVISION VMS
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - name: Remove all instances for the deployment_id
      shell: |
        cloud_instance delete -d {{ deployment_id }}
      register: instances
